location /api/admin/saveConfigFile {
    include /usr/local/openresty/lualib/flux_gate/core/api/conf/base_api.conf;
    access_by_lua_block {
        local fluxgateApiInterceptor = require("flux_gate/core/security/flux_gate_api_interceptor.lua")
        fluxgateApiInterceptor.intercept()
    }
    content_by_lua_file /usr/local/openresty/lualib/flux_gate/core/api/admin/config_file_provider.lua;
}

location ~ ^/api/admin/nginx/(updateUpstream|updateNameResolver)$ {
    include /usr/local/openresty/lualib/flux_gate/core/api/conf/base_api.conf;
    access_by_lua_block {
        local fluxgateApiInterceptor = require("flux_gate/core/security/flux_gate_api_interceptor.lua")
        fluxgateApiInterceptor.intercept()
    }
    content_by_lua_file /usr/local/openresty/lualib/flux_gate/core/api/admin/nginx_file_provider.lua;
}