location /api/admin/saveConfigFile {
    include /usr/local/openresty/lualib/flux_gate/core/api/conf/base_api.conf;
    access_by_lua_block {
        local basicAuthApiSecurityConfig = require("flux_gate/core/security/basic_auth_security_config")
        basicAuthApiSecurityConfig.config()
    }
    content_by_lua_file /usr/local/openresty/lualib/flux_gate/core/api/admin/config_file_provider.lua;
}

location ~ ^/api/admin/nginx/(updateUpstream|updateNameResolver)$ {
    include /usr/local/openresty/lualib/flux_gate/core/api/conf/base_api.conf;
    access_by_lua_block {
        local basicAuthApiSecurityConfig = require("flux_gate/core/security/basic_auth_security_config")
        basicAuthApiSecurityConfig.config()
    }
    content_by_lua_file /usr/local/openresty/lualib/flux_gate/core/api/admin/nginx_file_provider.lua;
}